(defproject net.unit8.job-streamer/job-streamer-agent "0.1.0-SNAPSHOT"
  :dependencies [[javax/javaee-api "7.0"]
                 [org.jberet/jberet-core "1.0.2.Final"]
                 [org.jberet/jberet-se "1.0.2.Final"]
                 [org.jboss.marshalling/jboss-marshalling "1.4.7.Final"]
                 [org.jboss.logging/jboss-logging "3.2.0.Final"]
                 [org.jboss.weld/weld-core "2.2.7.Final"]
                 [org.jboss.weld.se/weld-se "2.2.7.Final"]
                 [org.wildfly.security/wildfly-security-manager "1.1.2.Final"]
                 [com.google.guava/guava "18.0"]
                 [com.h2database/h2 "1.4.181"]

                 [org.clojure/clojure "1.6.0"]
                 [org.clojure/tools.logging "0.3.1"]
                 [org.clojure/data.xml "0.0.8"]
                 [org.clojure/core.async "0.1.346.0-17112a-alpha"]
                 [environ "1.0.0"]
                 [net.unit8.wscl/websocket-classloader "0.2.0"]
                 [net.unit8.logback/logback-websocket-appender "0.1.0"]
                 [io.undertow/undertow-websockets-jsr "1.1.1.Final"]
                 [liberator "0.12.2"]
                 [http-kit "2.1.17"]
                 [compojure "1.3.1"]
                 [ring/ring-defaults "0.1.2"]
                 [ring/ring-devel "1.3.2"]
                 [ch.qos.logback/logback-classic "1.1.2"]]

  :source-paths ["src/clj"]
  :java-source-paths ["src/java"]
  :plugins [[lein-ring "0.8.13"]]
  :main job-streamer.agent.core)
